# Experiment 7

## Aim:
Installing NS2 on Ubuntu & creating a basic network with two nodes & simulate data transfer between them.

---

## Theory:

- **NS2:**  
An open source discrete event simulator used for networking research.  
It uses TCL (Tool Command Language) to define the network topology & traffic.

- **NAM (Network Animator):**  
A visual tool used to view the network simulation traces generated by NS2.

- **Nodes & Links:**  
In NS2, nodes represent network devices & duplex links represent bi-directional communication paths with defined bandwidth & delay.

---

## Procedure:

### Step 1: Environment Setup

- Install Oracle VirtualBox & setup Ubuntu 20.04 LTS virtual machine  
- Open terminal in Ubuntu & update package list:

sudo apt-get update
*Install simulator & animation tool: sudo apt-get install ns2 nam gedit xgraph

Step 2: Script Creation
Create a new TCL file using text editor: gedit ex1.tcl

*Enter the following script:
set ns [new Simulator]
set nf [open out.nam w]
$ns namtrace-all $nf

set n0 [$ns node]
set n1 [$ns node]

$ns duplex-link $n0 $n1 1Mb 10ms DropTail

$ns at 1.0 "finish"

proc finish {} {
    global ns nf
    $ns flush-trace
    close $nf
    exec nam out.nam &
    exit 0
}

$ns run

Step 3: Execution
Run the simulation script from terminal: ns ex1.tcl

The NAM window will automatically open showing the two nodes
Click the Play button to observe the simulation

*Observations:

The terminal executes the TCL script without errors & the NAM tool successfully opens.
A simple topology consisting of two nodes connected by a single link is displayed visually.

*Result:

The NS2 environment was successfully configured on Ubuntu.
A basic point-to-point network simulation was executed & visualized using NAM.
